<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="15297" started-at="2020-12-22T03:09:40Z" finished-at="2020-12-22T03:09:55Z">
    <groups>
      <group name="functionalTest">
        <method signature="DemoTest.demoTest(java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.sample.test.demo.tests.DemoTest@2d928643]" name="demoTest" class="com.sample.test.demo.tests.DemoTest"/>
      </group> <!-- functionalTest -->
      <group name="smokeTest">
        <method signature="DemoTest.demoTest(java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.sample.test.demo.tests.DemoTest@2d928643]" name="demoTest" class="com.sample.test.demo.tests.DemoTest"/>
      </group> <!-- smokeTest -->
    </groups>
    <test name="Default test" duration-ms="15297" started-at="2020-12-22T03:09:40Z" finished-at="2020-12-22T03:09:55Z">
      <class name="com.sample.test.demo.tests.DemoTest">
        <test-method status="PASS" signature="init()[pri:0, instance:com.sample.test.demo.tests.DemoTest@2d928643]" name="init" is-config="true" duration-ms="3006" started-at="2020-12-22T03:09:40Z" finished-at="2020-12-22T03:09:43Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- init -->
        <test-method status="FAIL" signature="demoTest(java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.sample.test.demo.tests.DemoTest@2d928643]" name="demoTest" duration-ms="12179" started-at="2020-12-22T03:09:43Z" description="validate positive, negative and other scenerios" data-provider="pizzaForTestData" finished-at="2020-12-22T03:09:55Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[usernameTest]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[test@gmail.com]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[5555555555]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
placing order text is not displayed and same]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
placing order text is not displayed and same
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
at com.sample.page.demo.PizzaOrderFormPage.pizzaOrder(PizzaOrderFormPage.java:104)
at com.sample.test.demo.tests.DemoTest.demoTest(DemoTest.java:31)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- demoTest -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.sample.test.demo.tests.DemoTest@2d928643]" name="tearDown" is-config="true" duration-ms="93" started-at="2020-12-22T03:09:55Z" finished-at="2020-12-22T03:09:55Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.sample.test.demo.tests.DemoTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
